# Generated by Django 5.1.7 on 2025-03-30 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_lop', models.CharField(max_length=10, unique=True, verbose_name='Mã lớp')),
                ('ten_lop', models.CharField(max_length=100, verbose_name='Tên lớp')),
            ],
            options={
                'verbose_name': 'Lớp',
                'verbose_name_plural': 'Danh sách lớp',
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sinh_vien', models.CharField(help_text='Mã số sinh viên duy nhất', max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('ho_ten', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(verbose_name='Ngày sinh')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Mã QR')),
                ('lop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diemdanh.lop', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Danh sách sinh viên',
                'ordering': ['ma_sinh_vien'],
            },
        ),
        migrations.CreateModel(
            name='DiemDanh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian điểm danh')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diemdanh.sinhvien', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Danh sách điểm danh',
                'ordering': ['-thoi_gian'],
            },
        ),
    ]
