# Generated by Django 5.1.7 on 2025-04-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diemdanh', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_khoa', models.CharField(max_length=10, unique=True, verbose_name='Mã khoa')),
                ('ten_khoa', models.CharField(max_length=100, verbose_name='Tên khoa')),
            ],
            options={
                'verbose_name': 'Khoa',
                'verbose_name_plural': 'Danh sách khoa',
            },
        ),
        migrations.AddField(
            model_name='lop',
            name='khoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diemdanh.khoa', verbose_name='Khoa'),
        ),
    ]
